sonar.projectKey=frontend_EspritTech
sonar.projectName=Frontend EspritTech
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=squ_a9da42105b3f28d7fcf9e3404087327f85a94357
